# joblib versus pickle

**joblib** is usually significantly faster on large numpy arrays over **pickle** and **cpickle**

In [1]:
import pandas as pd
from sklearn import linear_model

df = pd.read_csv("https://raw.githubusercontent.com/laxmankusuma/Data-Science-series/main/Machine%20Learning/Salary_Data.csv",sep=',')
model = linear_model.LinearRegression()
model.fit(df[['YearsExperience']],df['Salary'])

LinearRegression()

# pickle

In [2]:
import pickle

In [3]:
with open('model_pickle','wb') as f:
    pickle.dump(model,f)

In [4]:
with open('model_pickle','rb') as f:
    mp = pickle.load(f)

In [5]:
model.predict([[1000]])

array([9475754.52165375])

In [6]:
mp.predict([[1000]])

array([9475754.52165375])

# joblib

In [7]:
import joblib

In [8]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [9]:
mj = joblib.load('model_joblib')

In [10]:
model.predict([[1000]])

array([9475754.52165375])

In [11]:
mj.predict([[1000]])

array([9475754.52165375])